### ISSUE TITLE
Consider encouraging people not to commit version numbers into bower.json files

### ISSUE THREAD

**Issue by matthew-andrews** [boennemann/grunt-semantic-release#14]
Firstly, great work with grunt-semantic-release.  Making releases is similarly horrible experience on [FastClick](https://github.com/ftlabs/fastclick) - and there is an even bigger problem of 'community initiated' packages out of our control .NET, rails, meteor, etc - that are running really old versions that we just don't have the time or expertise to keep up to date :-( so I can't tell you how much I agree that this is a problem that needs to be solved!

The `bower.json` spec actually discourages people from committing as bower uses git tags only:-
https://github.com/bower/bower.json-spec#version.

Could it be worth using this tool to encourage people to not include version numbers in their bower.json files?

**Comment by boennemann** [comment]
Thank you for your issue @matthew-andrews,

are you sure adding the version to the `bower.json` is actually discouraged? I mean sure it's not necessary at the moment, but it could also be used in the future. If I would have to do it manually I'd probably skip this step, but it's automated now.

So could you please elaborate on whether adding the version to `bower.json` does any harm I'm not seeing currently?

Best,
Stephan

**Comment by gr2m** [comment]
As the version gets added automatically, and people are strongly discouraged to touch version numbers anywhere when using grunt-semantic-release, I don't see a big problem in this particular case

**Comment by boennemann** [comment]
With the new `semantic-release` it's not even needed to put the version number inside the package.json any longer :)

https://github.com/boennemann/semantic-release
