### ISSUE TITLE
Why is the email and name a required option?

### ISSUE THREAD

**Issue by yfr** [boennemann/grunt-semantic-release#16]
It says its for git commits but can't you use the already setup email and username from git?

This settings are making it difficult to use as a setup task for a whole project with multiple contributors. Or do i miss something?

**Comment by boennemann** [comment]
These are the credentials for the release commits created on Travis CI, where none are set by default.  You can either use your own, make up something like "releasebot" or use nothing at all and you'll get "undefined".

Best

Stephan

**Comment by yfr** [comment]
I see. Thanks for clearing that up!
