### ISSUE TITLE
make remote test / build optional

### ISSUE THREAD

**Issue by gr2m** [boennemann/grunt-semantic-release#18]
related to #15.

Would it make sense to make a remote build platform optional? Instead, have optionally run all tests locally only, and do the git tags and npm publish and what not when all tests pass? Or would that be out of scope?
### My use case

A private web app that connects to an existing 3rd party API as the backend. Deployment is done via Github Pages. So my dream setup would be:
1. `grunt release`
2. run tests locally
3. When tests pass:
   a. create tag
   b. update CHANGELOG.md
   c. Create Release on Github
   d. push to `gh-pages` branch a.k.a. run `grunt deploy` task

**Comment by boennemann** [comment]
possible w/`semantic-release` https://github.com/boennemann/semantic-release
