### ISSUE TITLE
Plans to make it a seperate module without grunt dependency?

### ISSUE THREAD

**Issue by stefanjudis** [boennemann/grunt-semantic-release#7]
Hey,

this looks great and I'm just curious if you plan to extract it to make it usable without grunt to use it e.g. standalone or with gulp. :)

Thanks a lot.

**Comment by boennemann** [comment]
Hey @stefanjudis,

thank your very much for your feedback :)
While it's high on my agenda to make this plugin general purpose and as flexible as possible I don't think this will work w/o grunt anytime soon. This doesn't mean that the idea/workflow wouldn't work with e.g. gulp, but that the current implementation is tightly coupled to grunt.

Let me explain: Internally this tasks consumes, configures and executes 3rd party grunt-tasks like grunt-bump or grunt-conventional-changelog. It's not in my interest to reimplement them, so first they had to be standalone, too.

See also [caveats](https://github.com/boennemann/grunt-semantic-release#caveats) for more background.

I'll close this issue for now.

Thanks again for writing :)
Stephan

**Comment by stefanjudis** [comment]
Okay, makes sense when you're depending on third party grunt tasks. :)

Thanks for quick reply. :bowtie:

**Comment by boennemann** [comment]
Reopening for visibility

**Comment by boennemann** [comment]
`semantic-release` is a thing now. But beware it's different (i.e. better).

https://github.com/boennemann/semantic-release
